name: Generate-Netflix-CI

on:
  schedule:
    - cron: 0 16 * * *
  watch:
    types: [started]
  #push:
  #  branches: 
  #    - master
      
jobs:
  build:

    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@master
  
    - name: Init build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        runner_cpu="$(cat /proc/cpuinfo | grep 'model name')"
        cpu1="C CPU"
        cpu2="M CPU"
        result1=$(echo $runner_cpu | grep "cpu1")
        result2=$(echo $runner_cpu | grep "cpu2")
        if [[ "$result1""$result2"+ != "" ]]
        then
            echo "$(cat /proc/cpuinfo | grep 'model name')"
        else
            exit 1
        fi
        sudo -E apt-get update -y
        sudo -E apt-get install -y aggregate whois jq
        
    - name: Run generate script
      env: 
        LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
      run: | 
        chmod +x ./netflix_iprange.sh
        bash ./netflix_iprange.sh
        rm -f ./update.txt
        chmod +x ./mapcidr
        ./mapcidr -l ./NF_only.txt -o ./NOTMP.txt -sbh 65530
        cat ./NOTMP.txt > ./NF_only.txt
        rm -f ./NOTMP.txt
        ./mapcidr -l ./getflix.txt -o ./NOTMP.txt -sbh 65530
        cat ./NOTMP.txt > ./getflix.txt
        rm -f ./NOTMP.txt
        echo `date +%Y/%m/%d\ %H:%M:%S\ %Z` >> ./update.txt
      
    - name: Commit file
      run: |
        git config --global user.email simonsqiu@foxmail.com
        git config --global user.name SimonsQiu
        git add .
        git commit -m "Update `date +%Y/%m/%d\ %H:%M:%S\ %Z`" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
          
    - name: Cleanup Workflow Logs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
